version: '3'
services:
  tablero-frontend:
    build:
      context: tablero-frontend/.
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      - API_AUTH_URL:$API_AUTH_URL
      - API_GAME_URL:$API_GAME_URL
      - API_ADMIN_URL:$API_ADMIN_URL
      - API_GEOREF_URL:$API_GEOREF_URL
    image: ${APP_NAME}-tablero-frontend
    container_name: ${APP_NAME}-tablero-frontend
#    volumes:
#      - ./frontend:/app/${APP_NAME}-fe
    ports:
      - "4202:80"
    networks:
      - network # Conecta este servicio a la red ${APP_NAME}-network  


  admin-frontend:
    build:
      context: admin-frontend/.
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      - API_AUTH_URL:$API_AUTH_URL
      - API_GAME_URL:$API_GAME_URL
      - API_ADMIN_URL:$API_ADMIN_URL
      - API_GEOREF_URL:$API_GEOREF_URL
    image: ${APP_NAME}-admin-frontend
    container_name: ${APP_NAME}-admin-frontend
#    volumes:
#      - ./frontend:/app/${APP_NAME}-fe
    ports:
      - "4201:80"
    networks:
      - network # Conecta este servicio a la red ${APP_NAME}-network




  frontend:
    build:
      context: frontend/.
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      - API_AUTH_URL:$API_AUTH_URL
      - API_GAME_URL:$API_GAME_URL
      - API_ADMIN_URL:$API_ADMIN_URL
      - API_GEOREF_URL:$API_GEOREF_URL
    image: ${APP_NAME}-frontend
    container_name: ${APP_NAME}-frontend
#    volumes:
#      - ./frontend:/app/${APP_NAME}-fe
    ports:
      - "4200:80"
    networks:
      - network # Conecta este servicio a la red ${APP_NAME}-network

  backend:
    build:
      context: backend/.
      dockerfile: Dockerfile
    image: ${APP_NAME}-backend
    container_name: ${APP_NAME}-backend
    volumes:
      - ./backend:/app/Slamdunk.WebApi
      #- ./backend:/app/SISTEMA_BINGO_ONLINE
    ports:
      - "5214:5214"
    networks:
      - network # Conecta este servicio a la red ${APP_NAME}-network

  pgadmin:
    build:
      context: ./postgresdb/pgadmin
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "80:80"
    networks:
      - network

  postgres:
    build:
      context: ./postgresdb/postgres
    container_name: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: admindb
    ports:
      - "5432:5432"
    networks:
      - network

networks:
  network: # Define la red ${APP_NAME}-network
    driver: bridge # Utiliza el driver de red 'bridge' por defecto
