// <auto-generated />
using System;
using Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Slamdunk.WebApi.Migrations
{
    [DbContext(typeof(UserContext))]
    [Migration("20260807152459_migracion1")]
    partial class migracion1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Models.Images", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<byte[]>("Imagen")
                        .HasColumnType("bytea");

                    b.Property<string>("NombreImagen")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("images");
                });

            modelBuilder.Entity("Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("prueba_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Age")
                        .HasColumnType("integer")
                        .HasColumnName("edad");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nombre");

                    b.HasKey("Id");

                    b.ToTable("Prueba");
                });

            modelBuilder.Entity("Slamdunk.WebApi.Models.Carton", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("JugadaId")
                        .HasColumnType("integer");

                    b.Property<int?>("TokenId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("JugadaId");

                    b.HasIndex("TokenId");

                    b.ToTable("Cartones");
                });

            modelBuilder.Entity("Slamdunk.WebApi.Models.Ganador", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CartonId")
                        .HasColumnType("integer");

                    b.Property<int>("JugadaId")
                        .HasColumnType("integer");

                    b.Property<int>("PremioId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CartonId");

                    b.HasIndex("JugadaId");

                    b.HasIndex("PremioId");

                    b.ToTable("Ganadores");
                });

            modelBuilder.Entity("Slamdunk.WebApi.Models.Jugada", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("NumeroJugada")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Jugadas");
                });

            modelBuilder.Entity("Slamdunk.WebApi.Models.Jugador", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Alias")
                        .HasColumnType("text");

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CorreoElectronico")
                        .HasColumnType("text");

                    b.Property<string>("Dni")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Telefono")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Jugadores");
                });

            modelBuilder.Entity("Slamdunk.WebApi.Models.NumeroCarton", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CartonId")
                        .HasColumnType("integer");

                    b.Property<bool>("Marcado")
                        .HasColumnType("boolean");

                    b.Property<int>("NLinea")
                        .HasColumnType("integer");

                    b.Property<int>("Numero")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CartonId");

                    b.ToTable("NumerosCarton");
                });

            modelBuilder.Entity("Slamdunk.WebApi.Models.NumeroSorteado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("JugadaId")
                        .HasColumnType("integer");

                    b.Property<int>("Numero")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("JugadaId");

                    b.ToTable("NumerosSorteados");
                });

            modelBuilder.Entity("Slamdunk.WebApi.Models.Premio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("JugadaId")
                        .HasColumnType("integer");

                    b.Property<decimal>("Valor")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("JugadaId");

                    b.ToTable("Premios");
                });

            modelBuilder.Entity("Slamdunk.WebApi.Models.Tbl1DtsVariables", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Valor")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Variable")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Tbl1DtsVariables");
                });

            modelBuilder.Entity("Slamdunk.WebApi.Models.Token", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("JugadorId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("JugadorId");

                    b.ToTable("Tokens");
                });

            modelBuilder.Entity("Slamdunk.WebApi.Models.Carton", b =>
                {
                    b.HasOne("Slamdunk.WebApi.Models.Jugada", "Jugada")
                        .WithMany("Cartones")
                        .HasForeignKey("JugadaId");

                    b.HasOne("Slamdunk.WebApi.Models.Token", "Token")
                        .WithMany("Cartones")
                        .HasForeignKey("TokenId");

                    b.Navigation("Jugada");

                    b.Navigation("Token");
                });

            modelBuilder.Entity("Slamdunk.WebApi.Models.Ganador", b =>
                {
                    b.HasOne("Slamdunk.WebApi.Models.Carton", "Carton")
                        .WithMany()
                        .HasForeignKey("CartonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Slamdunk.WebApi.Models.Jugada", "Jugada")
                        .WithMany("Ganadores")
                        .HasForeignKey("JugadaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Slamdunk.WebApi.Models.Premio", "Premio")
                        .WithMany()
                        .HasForeignKey("PremioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Carton");

                    b.Navigation("Jugada");

                    b.Navigation("Premio");
                });

            modelBuilder.Entity("Slamdunk.WebApi.Models.NumeroCarton", b =>
                {
                    b.HasOne("Slamdunk.WebApi.Models.Carton", "Carton")
                        .WithMany("Numeros")
                        .HasForeignKey("CartonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Carton");
                });

            modelBuilder.Entity("Slamdunk.WebApi.Models.NumeroSorteado", b =>
                {
                    b.HasOne("Slamdunk.WebApi.Models.Jugada", "Jugada")
                        .WithMany()
                        .HasForeignKey("JugadaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Jugada");
                });

            modelBuilder.Entity("Slamdunk.WebApi.Models.Premio", b =>
                {
                    b.HasOne("Slamdunk.WebApi.Models.Jugada", "Jugada")
                        .WithMany("Premios")
                        .HasForeignKey("JugadaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Jugada");
                });

            modelBuilder.Entity("Slamdunk.WebApi.Models.Token", b =>
                {
                    b.HasOne("Slamdunk.WebApi.Models.Jugador", "Jugador")
                        .WithMany("Tokens")
                        .HasForeignKey("JugadorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Jugador");
                });

            modelBuilder.Entity("Slamdunk.WebApi.Models.Carton", b =>
                {
                    b.Navigation("Numeros");
                });

            modelBuilder.Entity("Slamdunk.WebApi.Models.Jugada", b =>
                {
                    b.Navigation("Cartones");

                    b.Navigation("Ganadores");

                    b.Navigation("Premios");
                });

            modelBuilder.Entity("Slamdunk.WebApi.Models.Jugador", b =>
                {
                    b.Navigation("Tokens");
                });

            modelBuilder.Entity("Slamdunk.WebApi.Models.Token", b =>
                {
                    b.Navigation("Cartones");
                });
#pragma warning restore 612, 618
        }
    }
}
